# Generated by Django 4.2.9 on 2024-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_payment_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_webhook',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
