# Generated by Django 4.2.9 on 2024-02-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0003_alter_payment_webhook_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_webhook',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payment_webhook',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='registration_app.customuser'),
            preserve_default=False,
        ),
    ]
