# Generated by Django 4.2.9 on 2024-02-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_alter_payment_webhook_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_webhook',
        ),
    ]
