# Generated by Django 4.2.9 on 2024-02-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0007_payment_webhook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_webhook',
        ),
    ]
