# Generated by Django 4.2.9 on 2024-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_payment_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_webhook',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
