# Generated by Django 5.0.6 on 2024-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_education_remove_all_scholarship_scholarship_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='All_Scholarship',
            field=models.CharField(default='Default Value', max_length=100),
        ),
    ]
