# Generated by Django 5.0.2 on 2024-05-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0003_scholarship_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('All_Scholarship', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approval', models.CharField(max_length=30)),
                ('Rejected', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eligibility1', models.CharField(max_length=30)),
                ('Eligibility2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=30)),
                ('Plan_Amount', models.IntegerField()),
                ('PLan_Duration', models.CharField(max_length=30)),
                ('Plan_Description', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('States', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_Name', models.CharField(max_length=30)),
                ('l_Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Mob', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.category')),
                ('Education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.education')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholarship_name', models.CharField(max_length=30)),
                ('Offered_by', models.CharField(max_length=30)),
                ('Plan_status', models.CharField(max_length=30)),
                ('Award', models.IntegerField()),
                ('Time_field', models.TimeField(auto_now_add=True)),
                ('Published_date', models.DateField(auto_now_add=True)),
                ('Dead_line', models.DateField(auto_now_add=True)),
                ('All_Scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.all_scholarship')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.category')),
                ('Eligibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.eligibility')),
                ('States', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.states')),
            ],
        ),
    ]
