# Generated by Django 5.0.2 on 2024-05-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0004_all_scholarship_approval_category_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Re_Password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='States',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.states'),
        ),
    ]
