# Generated by Django 5.0.2 on 2024-05-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0006_remove_register_age_register_dob_register_u_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship_details',
            name='Scholarship_logo',
            field=models.FileField(null=True, upload_to='scholarship_logo'),
        ),
    ]
