# Generated by Django 5.0.2 on 2024-05-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0008_scholarship_details_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Re_Password',
        ),
    ]
