# Generated by Django 5.0.2 on 2024-05-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0009_remove_register_re_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_Category', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship_details',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Category',
        ),
        migrations.AddField(
            model_name='register',
            name='S_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.s_category'),
        ),
        migrations.AddField(
            model_name='scholarship_details',
            name='S_CategoryCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.s_category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
