# Generated by Django 5.0.2 on 2024-05-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0010_s_category_remove_scholarship_details_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_category',
            old_name='s_Category',
            new_name='S_Category',
        ),
        migrations.RenameField(
            model_name='scholarship_details',
            old_name='S_CategoryCategory',
            new_name='S_Category',
        ),
    ]
