# Generated by Django 5.0.2 on 2024-06-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0011_rename_s_category_s_category_s_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('u_father', models.CharField(max_length=30)),
                ('u_f_mob', models.IntegerField()),
                ('u_mother', models.CharField(max_length=30)),
                ('u_m_mob', models.IntegerField()),
                ('u_image', models.FileField(null=True, upload_to='user_image')),
                ('u_certificate', models.FileField(null=True, upload_to='user_certificate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Scholarshipapp.register')),
            ],
        ),
    ]
