# Generated by Django 5.0.2 on 2024-06-02 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0012_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=30)),
                ('plan_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_date', models.DateTimeField(auto_now_add=True)),
                ('u_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.user_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.register')),
            ],
        ),
    ]
