# Generated by Django 5.0.2 on 2024-06-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0013_user_plan_userplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPlan',
            new_name='UserPlanScholarship',
        ),
    ]
