# Generated by Django 5.0.2 on 2024-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0015_user_plan_plan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship_details',
            name='All_Scholarship',
        ),
        migrations.RemoveField(
            model_name='scholarship_details',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='scholarship_details',
            name='Eligibility',
        ),
        migrations.RemoveField(
            model_name='scholarship_details',
            name='S_Category',
        ),
        migrations.RemoveField(
            model_name='scholarship_details',
            name='States',
        ),
        migrations.AddField(
            model_name='scholarship_details',
            name='All_Scholarship',
            field=models.ManyToManyField(blank=True, to='Scholarshipapp.all_scholarship'),
        ),
        migrations.AddField(
            model_name='scholarship_details',
            name='Education',
            field=models.ManyToManyField(blank=True, to='Scholarshipapp.education'),
        ),
        migrations.AddField(
            model_name='scholarship_details',
            name='Eligibility',
            field=models.ManyToManyField(blank=True, to='Scholarshipapp.eligibility'),
        ),
        migrations.AddField(
            model_name='scholarship_details',
            name='S_Category',
            field=models.ManyToManyField(blank=True, to='Scholarshipapp.s_category'),
        ),
        migrations.AddField(
            model_name='scholarship_details',
            name='States',
            field=models.ManyToManyField(blank=True, to='Scholarshipapp.states'),
        ),
    ]
