# Generated by Django 5.0.2 on 2024-06-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0016_remove_scholarship_details_all_scholarship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcoming_scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_schol_name', models.CharField(max_length=30)),
                ('up_schol_publish_date', models.DateField(auto_now_add=True)),
                ('up_schol_publish_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='scholarship_details',
            name='Scholar_Description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='applied_scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.scholarship_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.register')),
            ],
        ),
    ]
