# Generated by Django 5.0.2 on 2024-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0018_alter_scholarship_details_dead_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Mob',
            field=models.CharField(max_length=10),
        ),
    ]
