# Generated by Django 5.0.2 on 2024-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0019_alter_register_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xam_date', models.DateField(blank=True, null=True)),
                ('xam_name', models.CharField(max_length=50)),
            ],
        ),
    ]
