# Generated by Django 5.0.2 on 2024-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0020_exam_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='u_f_mob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='u_m_mob',
            field=models.CharField(max_length=10),
        ),
    ]
