# Generated by Django 5.0.2 on 2024-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0021_alter_user_profile_u_f_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming_scholarship',
            name='up_schol_publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
