# Generated by Django 5.0.2 on 2024-06-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0022_alter_upcoming_scholarship_up_schol_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_scholarship',
            name='applied_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='my_wislist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.scholarship_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.register')),
            ],
        ),
    ]
