# Generated by Django 5.0.2 on 2024-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0023_alter_applied_scholarship_applied_on_my_wislist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_wislist',
            name='scholarship',
        ),
        migrations.AddField(
            model_name='my_wislist',
            name='scholarship',
            field=models.ManyToManyField(to='Scholarshipapp.scholarship_details'),
        ),
    ]
