# Generated by Django 5.0.2 on 2024-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0024_remove_my_wislist_scholarship_my_wislist_scholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_wislist',
            old_name='scholarship',
            new_name='scholarships',
        ),
    ]
