# Generated by Django 5.0.2 on 2024-06-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0026_rename_my_wislist_my_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='Approval',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='Rejected',
        ),
        migrations.AddField(
            model_name='approval',
            name='applied_scholarship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.applied_scholarship'),
        ),
        migrations.AddField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Scholarshipapp.register'),
        ),
    ]
