# Generated by Django 4.2.7 on 2024-06-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarshipapp', '0027_remove_approval_approval_remove_approval_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship_details',
            name='Plan_status',
        ),
        migrations.RemoveField(
            model_name='scholarship_details',
            name='Time_field',
        ),
    ]
